export const developers = [
  {
    id: "DEV-001",
    slug: "longs-pemun",
    name: "Longs Pemun Gotar",
    role: "Blockchain Engineer",
    initials: "LP",
    avatar: "assets/images/devlongs.jpg",
    available: true,
    location: "Dubai, UAE",
    experience: "15 yrs exp.",
    differ: "",
    dob: "March 14, 2001",
    email: "longs@longspemun.dev",
    phone: "+971 50 314 7823",
    website: "longspemun.dev",
    bio: "Fifteen years in and blockchain still gets me out of bed. I've architected decentralised protocols, shipped production-grade smart contracts across EVM and non-EVM chains, and advised startups navigating the gap between Web2 infrastructure and Web3 ambition. I don't just write contracts — I think about the economic models behind them, the attack surfaces within them, and the users who will ultimately trust them. If you're building something that needs to last on-chain, let's talk.",
    skills: ["Solidity", "Rust", "Ethereum", "Hardhat", "Smart Contracts", "DeFi Protocols", "Web3.js", "IPFS", "Layer 2 Solutions", "Tokenomics", "Foundry", "Cairo"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-002",
    slug: "shaaibu-suleiman",
    name: "Sha'aibu Suleiman",
    role: "Protocol Engineer",
    initials: "SS",
    avatar: "https://avatars.githubusercontent.com/u/83074207?v=4",
    available: true,
    location: "Amsterdam, Netherlands",
    experience: "8 yrs exp.",
    differ: "",
    dob: "July 22, 2000",
    email: "shaaibu@shaaibu.dev",
    phone: "+31 6 2847 5931",
    website: "shaaibu.dev",
    bio: "I work at the layer most engineers never see — designing and implementing the protocols that everything else depends on. Eight years of thinking in terms of handshakes, state machines, consensus, and fault tolerance has given me a rare kind of systems intuition. Whether it's network protocol design, p2p communication layers, or distributed coordination, I'm comfortable in the deep end.",
    skills: ["Go", "Rust", "TCP/IP", "gRPC", "Distributed Systems", "Consensus Algorithms", "libp2p", "Protocol Buffers", "C++", "Network Engineering", "WebRTC", "ZeroMQ"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-003",
    slug: "akinlade-temitope",
    name: "Akinlade Temitope",
    role: "Software Developer",
    initials: "AT",
    avatar: "https://avatars.githubusercontent.com/u/172043375?v=4",
    available: true,
    location: "Nairobi, Kenya",
    experience: "2 yrs exp.",
    differ: "",
    dob: "September 5, 2002",
    email: "tope@akinlade.dev",
    phone: "+254 712 348 901",
    website: "akinlade.dev",
    bio: "Two years in and I'm already obsessed with writing code that's clean, readable, and actually maintainable. I'm comfortable across the stack, quick to pick up new tools, and I bring a genuine curiosity to every problem I touch. Still early in the journey — but moving fast.",
    skills: ["JavaScript", "React", "Node.js", "HTML", "CSS", "Tailwind CSS", "Git", "REST APIs"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-004",
    slug: "bankat-mananuf",
    name: "Bankat Mananuf",
    role: "Software Engineer",
    initials: "BM",
    avatar: "https://avatars.githubusercontent.com/u/36538962?v=4",
    available: true,
    location: "Prague, Czech Republic",
    experience: "6 yrs exp.",
    differ: "",
    dob: "January 18, 2001",
    email: "bankat@bankat.dev",
    phone: "+420 601 273 849",
    website: "bankat.dev",
    bio: "Six years of building production software across different domains has taught me that good engineering is mostly about tradeoffs — knowing when to optimise, when to ship, and when to refactor. I write robust backend services, design sensible APIs, and care deeply about the reliability of what I put into the world.",
    skills: ["Python", "Django", "PostgreSQL", "Docker", "REST APIs", "TypeScript", "Redis", "AWS", "CI/CD", "Linux"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-005",
    slug: "yilrit-dimka",
    name: "Yilrit Dimka",
    role: "AI/ML Engineer",
    initials: "YD",
    avatar: "https://avatars.githubusercontent.com/u/110455012?v=4",
    available: true,
    location: "Seoul, South Korea",
    experience: "7 yrs exp.",
    differ: "",
    dob: "April 30, 2000",
    email: "yilrit@yilrit.dev",
    phone: "+82 10 4821 3374",
    website: "yilrit.dev",
    bio: "I build intelligent systems — the kind that get better with data, generalise to new inputs, and actually work outside a notebook. Seven years across research and industry means I understand both the theory and the reality of deploying ML at scale. From feature engineering to model serving to monitoring drift in production, I've lived the full lifecycle.",
    skills: ["Python", "PyTorch", "TensorFlow", "Scikit-learn", "MLflow", "FastAPI", "Pandas", "NumPy", "LLM Fine-tuning", "Computer Vision", "NLP", "Kubernetes"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-006",
    slug: "andrew-miracle",
    name: "Andrew Miracle",
    role: "Software Engineer",
    initials: "AM",
    avatar: "assets/images/elcareem.jpeg",
    available: true,
    location: "Madrid, Spain",
    experience: "2 yrs exp.",
    differ: "",
    dob: "November 11, 2002",
    email: "andrew@andrewmiracle.dev",
    phone: "+34 612 849 031",
    website: "andrewmiracle.dev",
    bio: "Fresh enough to still find the craft exciting, experienced enough to ship things that work. I enjoy the full process — understanding requirements, thinking through architecture, writing the code, and seeing it land in users' hands.",
    skills: ["JavaScript", "React", "Node.js", "Express", "HTML", "CSS", "Git", "MongoDB"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-007",
    slug: "gamaliel-scholar",
    name: "Gamaliel Scholar Retkatmun",
    role: "Software Engineer",
    initials: "GS",
    avatar: "assets/images/scholar.jpeg",
    available: true,
    location: "Toronto, Canada",
    experience: "2 yrs exp.",
    differ: "",
    dob: "February 7, 2002",
    email: "scholar@gamaliel.dev",
    phone: "+1 416 823 5047",
    website: "gamaliel.dev",
    bio: "Software engineer with a scholar's mindset — I don't just solve the problem in front of me, I try to understand the class of problem it belongs to. Two years in and I'm building a strong foundation across both frontend and backend, with a particular interest in writing code that's easy for the next person to work with.",
    skills: ["JavaScript", "TypeScript", "React", "Node.js", "PostgreSQL", "Git", "REST APIs", "HTML", "CSS"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-008",
    slug: "ngwan-nenwarrangdung",
    name: "Ngwan Nenwarrangdung",
    role: "Software Engineer",
    initials: "NN",
    avatar: "https://avatars.githubusercontent.com/u/255333128?v=4",
    available: true,
    location: "Berlin, Germany",
    experience: "2 yrs exp.",
    differ: "",
    dob: "June 19, 2003",
    email: "ngwan@ngwan.dev",
    phone: "+49 157 2348 9012",
    website: "ngwan.dev",
    bio: "I write software that solves real problems and I take the quality of that work seriously — even at two years in. Currently sharpening my backend skills while staying sharp across the stack.",
    skills: ["Python", "JavaScript", "React", "Flask", "Node.js", "Git", "HTML", "CSS", "REST APIs"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-009",
    slug: "john-paul",
    name: "Ohakwe Johnpaul",
    role: "Software Engineer",
    initials: "JP",
    avatar: "assets/images/johnpaul.jpeg",
    available: true,
    location: "Lisbon, Portugal",
    experience: "5 yrs exp.",
    differ: "",
    dob: "August 23, 2001",
    email: "john@johnpaul.dev",
    phone: "+351 912 384 750",
    website: "johnpaul.dev",
    bio: "Five years of building software across startups and product teams has given me a well-rounded perspective on what good engineering actually looks like in practice. I care about clean interfaces, reliable systems, and writing code that doesn't become someone else's problem six months later. Comfortable leading features end-to-end and collaborating across design and product.",
    skills: ["JavaScript", "TypeScript", "React", "Node.js", "Express", "PostgreSQL", "Docker", "REST APIs", "Git", "Tailwind CSS"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  },

  {
    id: "DEV-010",
    slug: "dakshak",
    name: "Dakshak John",
    role: "QA Engineer",
    initials: "DK",
    avatar: "https://vintique-one.vercel.app/public/image/daksahkj.jpeg",
    available: true,
    location: "Mumbai, India",
    experience: "4 yrs exp.",
    differ: "",
    dob: "October 3, 2001",
    email: "hello@dakshak.dev",
    phone: "+91 98201 47362",
    website: "dakshak.dev",
    bio: "Quality isn't a phase at the end — it's a discipline built into every step. I bring four years of testing experience across manual, automated, and performance testing, with a strong instinct for finding the edge cases that slip through. I work closely with developers, not against them, and I think good QA makes the whole team faster.",
    skills: ["Selenium", "Cypress", "Jest", "Postman", "Python", "API Testing", "Performance Testing", "TestRail", "CI/CD", "JIRA", "Playwright", "Load Testing"],
    projects: [],
    links: { github: "", linkedin: "", portfolio: "" }
  }
];